site:
    base_url: https://exploring-data.com
    author: Ramiro Gómez
    feed_title: Exploring Data News Feed
    amazon_tag:
        us: xpdt-20

# Settings that affect collections in the document index. Top-level keys of
# collections can be used as document attributes for grouping it in the
# corresponding collection.
collections:
    tags:
        path: tags
        template: index.html
    shirt_collections:
        path: prints
        template: collections/prints.html

extensions:
    jinja:  # https://jinja.palletsprojects.com/extensions/
        - 'jinja2.ext.loopcontrols'
